/**
 * lib/narration.ts
 *
 * Static lookup helpers for LibriVox chapter narration audio.
 *
 * The two JSON files were generated by scripts/generate-narration-map.ts and
 * map each chapter's Roman numeral to a direct Archive.org MP3 URL.
 *
 * English (v3): David Clarke — 117 chapters, 54h 16m, public domain
 *   https://librivox.org/the-count-of-monte-cristo-version-3-by-alexandre-dumas/
 *
 * French: Jc Guan — 117 chapters, ~51.5h, public domain
 *   https://librivox.org/le-comte-de-monte-cristo-by-alexandre-dumas
 *
 * No network calls at render time — these are static imports resolved at
 * build time by Next.js.
 */

import enMap from "@/content/narration/en.json";
import frMap from "@/content/narration/fr.json";

export type NarrationLang = "en" | "fr";

const MAPS: Record<NarrationLang, Record<string, string>> = {
  en: enMap as Record<string, string>,
  fr: frMap as Record<string, string>,
};

export const NARRATION_NARRATOR: Record<NarrationLang, string> = {
  en: "David Clarke",
  fr: "Jc Guan",
};

export const NARRATION_SOURCE: Record<NarrationLang, string> = {
  en: "LibriVox (English, v3)",
  fr: "LibriVox (Français)",
};

export const NARRATION_LICENSE = "Public Domain";
export const NARRATION_LICENSE_URL =
  "https://librivox.org/pages/public-domain/";

/**
 * Returns the Archive.org MP3 URL for the given language and chapter Roman
 * numeral, or null if no recording is available.
 */
export function getNarrationUrl(
  lang: NarrationLang,
  chapterNum: string,
): string | null {
  return MAPS[lang][chapterNum.toUpperCase()] ?? null;
}

/**
 * Returns all languages that have a recording for the given chapter.
 */
export function getAvailableLangs(chapterNum: string): NarrationLang[] {
  const upper = chapterNum.toUpperCase();
  return (["en", "fr"] as NarrationLang[]).filter(
    (lang) => !!MAPS[lang][upper],
  );
}

/**
 * True if at least one language has narration for this chapter.
 */
export function hasNarration(chapterNum: string): boolean {
  return getAvailableLangs(chapterNum).length > 0;
}

/**
 * DOM id for the inline chapter narration player (used for scroll targeting).
 */
export const NARRATION_PLAYER_ID = "chapter-narration";
